image:
  file: .gitpod.Dockerfile

ports:
  - port: 8180
    visibility: private
    description: Keyloak

vscode:
  extensions:
    # Spring Boot Extension Pack
    - Pivotal.vscode-boot-dev-pack
    # Extension Pack for Java
    - vscjava.vscode-java-pack
    # XML
    - redhat.vscode-xml