image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Keyloak
    command: |
      docker compose up -d

ports:
  - port: 8180
    onOpen: notify
    description: Keyloak

vscode:
  extensions:
    # Spring Boot Extension Pack
    - Pivotal.vscode-boot-dev-pack
    # Extension Pack for Java
    - vscjava.vscode-java-pack
    # XML
    - redhat.vscode-xml
    # Gradle for Java
    - vscjava.vscode-gradle